# Site settings
title: Dr. Ryan
description: Dr. Ryan

# User settings
username: Kevin Ryan
user_description: I'm a Director of Data Science and Analytics with <b>15 years</b> experience applying machine learning and optimization methods to a wide range of applications, solving complex problems through data-driven decision-making. 
user_title: Director of Data Science
email: kevin.ryan7@gmail.com
exclude: ['package.json', 'src' , 'node_modules']
